### ISSUE TITLE
Evaluation of falconctl location is done on sensible controller

### ISSUE THREAD

**Issue by bufanda** [CrowdStrike/ansible_collection_falcon#157]
The method `self.module.get_bin_path` used in the plugins `falcon` and `falcon_info` is evaluated on the ansible controller and not on the client host thus it will fail when flacon isn't installed on the controller. 

https://github.com/CrowdStrike/ansible_collection_falcon/blob/3384aa63239f2eea98902bd42b529368f48d8538/plugins/modules/falconctl.py#L160

This could easily happen when containerised controller nodes are used like in CI/CD Pipelines in Drone
Tested with drone:2 and ansible:2.11 container.

**Comment by carlosmmatos** [comment]
@bufanda not sure I'm following this question/concern. The plugin executes on the desired managed nodes. You can look at how we run our molecule testing for reference in regards to ci/cd:

For Linux testing - the ansible control node is the GH runner ubuntu host (does not have falcon installed) running ansible against docker containers. It's clear from here that the plugins only execute on the managed nodes (containers), otherwise it would fail on the github runner itself.

For Windows it's very similar - the ansible control node is the GH runner MacOS (does not have falcon installed) running ansible against a vagrant windows vm image. Same applies here, the ansible code is executed against the managed windows node, otherwise it would fail on the macos GH runner itself.

Are you perhaps using `localhost` as a managed node?

**Comment by carlosmmatos** [comment]
Any update on this?

**Comment by redhatrises** [comment]
Closing. Please reopen when the logs can be provided.
