### ISSUE TITLE
Architecture key/value in API

### ISSUE THREAD

**Issue by redhatrises** [CrowdStrike/ansible_collection_falcon#16]
Need an OS architecture key/value pair in the API for sensor file downloads. This is to handle cases where, for example, we have an rpm for both 64-bit and ARM for Amazon Linux. A recommendation key/value pair would be:

```
{
    architecture: "x86_64"
}
```

Or for ARM:

```
{
    architecture: "aarch64"
}
```

The current invocation makes it harder to query for architecture specific downloads.

**Comment by redhatrises** [comment]
yes, because it is a better invocation vs where the data resides now.... even though we have worked around it.

**Comment by TyraelTLK** [comment]
Hi, is this related to the issues that we have since yesterday?
We are no more able to install CrowdStrike on RHEL7 and RHEL8:

  "msg": "Cannot add package /tmp/ansible.Kh9nuBfalcon/falcon-sensor-6.49.0-14606.el7.s390x.rpm to transaction. Not a compatible architecture: s390x\nError: Nothing to do\n",

  "msg": "Depsolve Error occurred: \n Problem: conflicting requests\n  - package falcon-sensor-6.49.0-14606.el8.s390x does not have a compatible architecture\n  - nothing provides config(falcon-sensor) = 6.49.0-14606.el8 needed by falcon-sensor-6.49.0-14606.el8.s390x\n  - nothing provides libc.so.6(GLIBC_2.2)(64bit) needed by falcon-sensor-6.49.0-14606.el8.s390x\n  - nothing provides libc.so.6(GLIBC_2.2.3)(64bit) needed by falcon-sensor-6.49.0-14606.el8.s390x\n  - nothing provides libdl.so.2(GLIBC_2.2)(64bit) needed by falcon-sensor-6.49.0-14606.el8.s390x\n  - nothing provides libm.so.6(GLIBC_2.2)(64bit) needed by falcon-sensor-6.49.0-14606.el8.s390x\n  - nothing provides libpthread.so.0(GLIBC_2.2)(64bit) needed by falcon-sensor-6.49.0-14606.el8.s390x\n  - nothing provides librt.so.1(GLIBC_2.2)(64bit) needed by falcon-sensor-6.49.0-14606.el8.s390x",


Since the availability of falcon sensors for s390x we got this error on x86_64 machines

**Comment by redhatrises** [comment]
@TyraelTLK please open a new issue for this. This is for having an architecture field in the api vs in the API field it is stored in as of today.

**Comment by carlosmmatos** [comment]
@redhatrises closing this as this is an internal ask to CS API team. We can just hope it get's supported.
