### ISSUE TITLE
RHEL 8 undefined variable error

### ISSUE THREAD

**Issue by Lobout** [CrowdStrike/ansible_collection_falcon#239]
when attempting to run falcon install i am getting an undefined variable error as follows:

```
{
  "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'json'\n\nThe error appears to be in '/runner/requirements_collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/api.yml': line 76, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: CrowdStrike Falcon | Get list of filtered Falcon sensors\n  ^ here\n",
  "_ansible_no_log": false
}
```

**Comment by carlosmmatos** [comment]
Hi @Lobout , it looks like there may be an issue with your API credentials, because the `dict` object error is referring to the output from the `- name: CrowdStrike Falcon | Authenticate to CrowdStrike API` task. First, make sure your API scope is correct per our [README](https://github.com/CrowdStrike/ansible_collection_falcon/blob/main/roles/falcon_install/README.md#falcon-api-permissions). 

To help you troubleshoot, run ansible like this:
```bash
$ ansible-playbook <your playbook> -vvv -e "falcon_api_enable_no_log=no"
```
This will give you the output from the API authentication tasks.

**Comment by Lobout** [comment]
> 

You are correct.  The person in charge of the api access did not set permissions correctly.  I hate generic error messages.   This is not a problem and can be closed.

**Comment by carlosmmatos** [comment]
@Lobout What's interesting is I don't even know how you got that message. If you authenticated with the API (assuming you had incorrect permissions), you would have got another message essentially saying access denied.. that message above is cryptic since what this is saying that you somehow authenticated to the api, but didn't receive a bearer token in the response.. which is strange.. Glad it's working now for you though.
