### ISSUE TITLE
[Enhancement] Use run_once for API calls

### ISSUE THREAD

**Issue by rnsc** [CrowdStrike/ansible_collection_falcon#260]
Hello,

I was wondering if the roles could be enhanced with the use of `run_once: true` for tasks that don't require to be run on all the hosts of an inventory.
ie:
https://github.com/CrowdStrike/ansible_collection_falcon/blob/327ad35e2c0a58864296a388fe46291e69554925/roles/falcon_install/tasks/api.yml#L2

It doesn't make sense to trigger a call to the API for all the hosts and can make the install/configure run longer than necessary.

WDYT?

**Comment by carlosmmatos** [comment]
@rnsc thanks for opening up the issue. I like the idea and I can see it making since for API authentication calls.. so in theory, if you are running this on X# of systems, we would just authenticate one time and register that bearer token, that would then be passed on to the other hosts in subsequent tasks... 

Let me mess around with this to see what we can come up with.

**Comment by rnsc** [comment]
> @rnsc thanks for opening up the issue. I like the idea and I can see it making sense for API authentication calls.. so in theory, if you are running this on X# of systems, we would just authenticate one time and register that bearer token, that would then be passed on to the other hosts in subsequent tasks...
> 
> Let me mess around with this to see what we can come up with.

To give you a bit more context:
I have environments that contain at least a hundred hosts, some even more and I get throttled very easily by the Crowdstrike API when, for example, reconfiguring tags on the endpoints.
So that means I have to batch the Ansible runs with `serial` and it's a bit impractical.

**Comment by rnsc** [comment]
I've tested with a local fork of this collection to unblock my current deployment and it looks ok. But I have the same OS distribution/versions everywhere so that's limiting the impact.

**Comment by carlosmmatos** [comment]
I've got something tested from yesterday that I plan on opening up a PR today. This is primarily for dealing with API authentication, as the token bearer works for all hosts so no need to run that on all. The other API calls we currently have are for querying for the sensor, sensor update policy query (if supplied), sensor kernel compat check (can be skipped), and sensor download. Most of these don't make sense to run once due to heterogeneous environments, with the exception maybe of the sensor update policy query. 

As for tags, that's not making any api calls, it's simply running the falconctl command. 

Happy to hash out other potential areas we can prevent api throttling with you once I open the PR.

**Comment by carlosmmatos** [comment]
> I've tested with a local fork of this collection to unblock my current deployment and it looks ok. But I have the same OS distribution/versions everywhere so that's limiting the impact.

If you have a homogeneous environment like this, are you using the API install method? Or are you using a local file or repo sensor install method? The latter would cut down significantly on API calls.

**Comment by rnsc** [comment]
> > I've tested with a local fork of this collection to unblock my current deployment and it looks ok. But I have the same OS distribution/versions everywhere so that's limiting the impact.
> 
> If you have a homogeneous environment like this, are you using the API install method? Or are you using a local file or repo sensor install method? The latter would cut down significantly on API calls.

I'm just using your collection with an API key yes. I didn't want to add a local repo for this to avoid having to maintain yet another thing internally. And I figured using the API would make sure when I install the agent I get the latest version that is compatible for my host.

**Comment by carlosmmatos** [comment]
Understood... as an fyi, we are working on creating/releasing version 4 which will make this much easier for you to manage as we move to a more api driven collection. So in the near future, you can use the crowdstrike.falcon.sensor_download module once to download the latest sensor, then run a copy command to copy it to your hosts, then run the install role using the local file method. This should cut down api call's significantly
