### ISSUE TITLE
win_install fails due to variable issue

### ISSUE THREAD

**Issue by dcacklam** [CrowdStrike/ansible_collection_falcon#294]
The win_install.yml contains a variable, 'falcon_cid' that is not defined anywhere else in the playbook.
This causes it to not properly transmit the Client ID (Which is stored as falcon_client_id everywhere else)

Temporarily, defining falcon_cid in the ansible.buildin.include_role section makes it work, but the right var should really be used.

**Comment by carlosmmatos** [comment]
Hi @dcacklam and thanks for opening an issue. 

So just for reference, the variables `falcon_cid` and `falcon_client_id` are two completely separate variables.

The `falcon_client_id` is part of your API credentials whereas the `falcon_cid` is a Customer ID - provided by CrowdStrike. Generally this is left blank if you are providing your API credentials because we will automatically retrieve the `falcon_cid` for you (see [auth.yml](https://github.com/CrowdStrike/ansible_collection_falcon/blob/main/roles/falcon_install/tasks/auth.yml#L42)). 

However, if you opt to install via local method (`falcon_install_method` != "api") - then you would need to provide the `falcon_cid` value as there is no way for us to get that for you. 

I hope this helps.

**Comment by carlosmmatos** [comment]
Example Playbook
----------------

How to set the Falcon Customer ID (CID) when CID is known:
```yaml
- hosts: all
  roles:
  - role: crowdstrike.falcon.falcon_configure
    vars:
      falcon_cid: 1234567890ABCDEF1234567890ABCDEF-12
```

**Comment by carlosmmatos** [comment]
@dcacklam Where you able to work through this?

**Comment by carlosmmatos** [comment]
closing due to no response for a while. If you feel like you would like to re-open this, please do so. Thanks.
