### ISSUE TITLE
Ubuntu Install Failing "The sensor version: 6.53.15003 is not supported with kernel: 5.4.0-137-generic"

### ISSUE THREAD

**Issue by ktinthecloud** [CrowdStrike/ansible_collection_falcon#337]
Getting the following error when targeting Ubuntu machines:

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Validate Sensor version is compatible with Kernel] ***************************************************************************************
task path: /home/user@domain.com/projects/ecco-se-ansible-crowdstrike/collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/api.yml:146
fatal: [testserver]: FAILED! => {
    "assertion": "falcon_sensor_version in falcon_base_package_supported_sensor_versions or falcon_sensor_version in falcon_ztl_supported_sensor_versions or falcon_sensor_version in falcon_ztl_module_supported_sensor_versions",
    "changed": false,
    "evaluated_to": false,
    "msg": "The sensor version: 6.53.15003 is not supported with kernel: 5.4.0-137-generic"
}

**Comment by ktinthecloud** [comment]
I used the **falcon_sensor_version_decrement: 1** variable and that seems to work.

**Comment by carlosmmatos** [comment]
@ktinthecloud Glad you found a sensor version supported for your kernel.

See the [Linux Supported Kernels](https://falcon.crowdstrike.com/documentation/245/linux-supported-kernels) docs to see if a sensor versions supported for your kernel.

If you wanted to bypass this check in ansible, you could use set: `falcon_skip_kernel_compat_check=yes` - however do note that this check is in place to essentially let you know that your configuration will most likely be in RFM mode due to unsupported configuration.
