### ISSUE TITLE
"CrowdStrike Falcon | Download Falcon Sensor Installation Package (local)" Behavior When falcon_sensor_version_decrement > 1

### ISSUE THREAD

**Issue by SalesColin** [CrowdStrike/ansible_collection_falcon#577]
Hello! First time submitting an issue here so please let me know if my format is off or details are missing!

When `falcon_sensor_version_decrement` is greater than 1, and there is only 1 version of the sensor available for a given OS, the "CrowdStrike Falcon | Download Falcon Sensor Installation Package (local)" task will fail with an error like this:

`{
  "msg": "The task includes an option with an undefined variable. The error was: list object has no element 2. list object has no element 2\n\nThe error appears to be in '/runner/requirements_collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/api.yml': line 71, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: CrowdStrike Falcon | Download Falcon Sensor Installation Package (local)\n  ^ here\n",
  "_ansible_no_log": false
}`

The above error message occurred when I ran this playbook on 11/21/2024 against a large inventory containing a small number of Ubuntu 24.04 hosts. This message appeared on every host with Ubuntu 24.04 as it's OS version, which tipped me off to where this issue was stemming from.

There may be infosec requirements at our organizations that require us to use the `falcon_sensor_version_decrement` value to keep us at a n-2 state by default. When we're running the installation across a large inventory of hosts, it is also difficult to ensure all hosts are at an OS version that has multiple falcon sensor versions available via the API.

Is this the intended behavior for the `falcon_sensor_version_decrement` variable? And if so, can that be added to the docs for the falcon_install role? Or could the error message be a little more descriptive to mention that the `falcon_sensor_version_decrement` variable is ultimately responsible for the error?

Another approach may be that if `falcon_sensor_version_decrement` is set to `x`, and the number of versions available for a particular OS are equal to `y` (where `y` is strictly less than `x`), it may be best to default to install the `y` version of the sensor. At least this way we are guaranteeing that the system is protected by the falcon sensor, even if it does not meet our initially requested version decrement.

Curious to hear your thoughts!

**Comment by SalesColin** [comment]
Howdy @carlosmmatos thanks for the reply 😄 

Honestly I agree with all your points here. I think your first bullet point is the best approach generally, since then the error message would then contain exactly the context someone needs to understand the problem at hand.

My specific use-case here is that we are running the falcon_install on a schedule through AWX on an inventory that includes every device in our infrastructure (sources defined from VMWare, physical hosts, etc). This is mostly a fallback plan in the event that a system was spun up without using a standard VM template or deployment process, so we can ensure the falcon sensor is always deployed everywhere. This is where my thought of "well if the falcon_install role could install any newer version of the sensor, that'd be better than having the job fail. The sensor update policies will decrement them to our desired value when it becomes available anyway". Using group/host vars and filtering on OS major is a slick solution for this and I appreciate the input!

Internally we are using sensor update policies + host groups in the UI to control versions as well, we were just hoping to install them at the required decrement so we don't have the interim period where the sensor has to downgrade itself after install. It is a small problem to have 😆.

**Comment by carlosmmatos** [comment]
Hey @SalesColin - so really in your scenario there are two things to consider:
1. Since you are internally using sensor update policies - this will control the version of the sensor from the cloud, as opposed to the actual binary (rpm/deb) package. That is fine and what some customers do who don't prefer to have full binary (rpm/deb) package control is either they install the latest from the API and let the policy downgrade/manage the version - or they install install a downloaded binary (usually older for the older distros) and let the policies upgrade them from there.
    1. The key thing to consider here is that there is that the sensor update policies don't actually manage the binary/package version. They update the internal db of the currently installed sensor accordingly to whatever version is required. So in this case, you only ever really need to install the sensor once, and then let the cloud updates manage the lifecycle.
1. Secondly, if you want to have full control of package management from a rpm/deb perspective, then you should consider **not** using sensor update policies. Essentially, with the `falcon_install` role you can do the same thing that sensor update policies do by utilizing the `falcon_sensor_version_decrement` and use Ansible inventory host/group vars to manage OS distro differences. Alternatively you can always pick a sensor version and use the `falcon_sensor_version` variable to ensure the same version is always used instead of letting the API determine a certain version based on availability. This will make sure your binary packages are in updated/downgraded accordingly instead of doing cloud updates.

My point is you have options and flexibility to determine the best fit for your environment with Ansible. 

Oh, I should also mention (based on your use-case about running an AWX job on a schedule to ensure compliance on systems that don't have Falcon installed) that we also have a dynamic inventory that may help you address this and only target the "unmanaged" systems instead of ALL systems. Check it out: [crowdstrike.falcon.falcon_discover](https://crowdstrike.github.io/ansible_collection_falcon/falcon_discover_inventory.html).
> There are a few examples I give in there for the filters that you can use to target what we refer to as _unmanaged_ (assets in your environment that we discovered not to have the falcon sensor installed). For example:
> ```
> # return unmanaged assets discovered in the past day
> #filter: "entity_type:'unmanaged'+first_seen_timestamp:>'now-1d'"
> ```
