### ISSUE TITLE
Please support --check option

### ISSUE THREAD

**Issue by philrumble-fz** [CrowdStrike/ansible_collection_falcon#85]

**Comment by redhatrises** [comment]
Hello. Thank you for opening this.

We don't support `--check` mode due to the use of the command module in conjunction with the falcon backend. Both combined make check mode very difficult to support, so we won't be supporting it in its current invocation. 

That said, we are working on an ansible module that should alleviate some of the current problems around this. We would expect this to be handled there.

Closing due to will not support in its current invocation and as already complete for current development cycle.
